name: Generate snake game

on:
  schedule:
    # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
